<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Request\Http');
$isCheckoutPage = $request->getFullActionName() == 'checkout_index_index';

if ($isCheckoutPage) {
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $storeInformation = $objectManager->create('Magento\Store\Model\Information');
    $store = $objectManager->create('Magento\Store\Model\Store');
    $storeInfo = $storeInformation->getStoreInformationObject($store);
    $phone = $storeInfo->getPhone();

    if ($customerSession->isLoggedIn()) {
        $customer = $customerSession->getCustomer();
        $customerName = $customer->getName();

        echo '<div class="our-phone">Добро пожаловать, ' . $customerName . '! ' . 'Нужна помощь в оформлении заказа? позвоните нам в ' . $phone . '</div>';
    }
}
?>
